// Copyright (c) 2026 Tomasz Ziajko
// SPDX-License-Identifier: GPL-3.0-only
// Commercial license available — see README

#ifndef CHIPZ_ISR_SOURCE_HPP
#define CHIPZ_ISR_SOURCE_HPP

#include <cstdint>

namespace chipz {

/**
 * @brief Logical identifiers for hardware interrupt sources
 *
 * Chips declare which sources they require via
 * ChipBase::requiredISRs(). Core builds a dispatch table from this
 * at add() time, and routes fired ISRs to the owning chip during
 * service() pass 1 — deferred from interrupt context.
 *
 * These cover non-communication interrupt sources (GPIO, timers, CAN events).
 * Communication events (I2C transfer complete, SPI done, etc.) are handled
 * via CommunicationInterface::notify*() and the CommEntry routing path.
 *
 * Platform ISR handlers that call Core::onISR() are generated by
 * chipz_generate_isrs() in cmake/ChipzISR.cmake.
 *
 * Constraint: at most one chip may register for any single ISRSource.
 * For STM32 shared vectors (EXTI5_9, EXTI10_15) this means at most one
 * chip per group, regardless of which specific pin it uses.
 */
enum class ISRSource : uint8_t {
    // GPIO external interrupt lines
    EXTI0,
    EXTI1,
    EXTI2,
    EXTI3,
    EXTI4,
    EXTI5_9,    ///< STM32: lines 5-9 share one vector (EXTI9_5_IRQHandler)
    EXTI10_15,  ///< STM32: lines 10-15 share one vector (EXTI15_10_IRQHandler)

    // Hardware timers for peripheral use (not Core's scheduler timer)
    TIM1,
    TIM2,
    TIM3,
    TIM4,
    TIM5,
    TIM6,
    TIM7,
    TIM8,

    // CAN bus event interrupts (e.g. TJA1145 wake-up via CAN)
    CAN1_TX,
    CAN1_RX0,
    CAN1_RX1,
    CAN1_SCE,
    CAN2_TX,
    CAN2_RX0,
    CAN2_RX1,
    CAN2_SCE,

    COUNT ///< Sentinel — must be last; do not use as an ISR source
};

} // namespace chipz

#endif // CHIPZ_ISR_SOURCE_HPP
